import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Montserrat,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { WeddingProvider } from "@/context/WeddingContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-names",
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",

  title: "Cưới Thôi",
  description: "Tạo thiệp cưới online dễ thương, gửi liền tay – Cưới thôi!",
  openGraph: {
    title: "Cưới Thôi",
    description: "Thiệp cưới online siêu nhanh, siêu xinh, siêu dễ thương.",
    url: "https://cuoithoi.vercel.app",
    siteName: "Cưới Thôi",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Cưới Thôi - Thiệp cưới online",
      },
    ],
    locale: "vi_VN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Cưới Thôi",
    description: "Thiệp cưới online dễ thương, chia sẻ liền tay!",
    images: ["/og-image.jpg"],
  },
  keywords: ["thiệp cưới", "thiệp cưới online", "thiệp mời", "cưới thôi"],
  authors: [{ name: "Cưới Thôi Team" }],
  metadataBase: new URL("https://cuoithoi.vercel.app"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${inter.variable} ${montserrat.variable} antialiased`}
      >
        <ClerkProvider>
          <WeddingProvider>{children}</WeddingProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
